- updated for 1.3.8
Changed files:
    gzip-mktemp.patch -> 1.7
    gzip-noppid.patch -> 1.5
    gzip-stderr.patch -> 1.4

diff --git a/gzip-mktemp.patch b/gzip-mktemp.patch
--- a/gzip-mktemp.patch
+++ b/gzip-mktemp.patch
@@ -1,19 +1,11 @@
---- gzip-1.3.6/gzexe.in.orig	2006-11-20 09:40:33.000000000 +0100
-+++ gzip-1.3.6/gzexe.in	2006-11-29 23:50:44.730531500 +0100
-@@ -132,12 +132,12 @@
-     (sed 1q $0 &&
-      sed "s|^if tail|if $tail|" <<'EOF' &&
- skip=26
--set -C
-+
- umask=`umask`
- umask 77
--if (tempfile --version) >/dev/null 2>&1
--then gztmp=`tempfile -p gztmp` || exit
--else gztmp=/tmp/gztmp$$
-+if (mktemp -V) >/dev/null 2>&1
-+then gztmp=`mktemp ${TMPDIR:-/tmp}/gztmp$$.XXXXXX` || exit
-+else { echo 'cannot create temporary file' >&2; exit 1; }
- fi
- if tail +$skip "$0" | "BINDIR"/gzip -cd > "$gztmp"; then
-   umask $umask
+--- gzip-1.3.8/gzexe.in.orig	2006-12-09 07:58:27.000000000 +0100
++++ gzip-1.3.8/gzexe.in	2006-12-13 00:18:18.193363272 +0100
+@@ -161,7 +161,7 @@
+ if type mktemp >/dev/null 2>&1; then
+   gztmpdir=`mktemp -dt`
+ else
+-  gztmpdir=/tmp/gztmp$$; mkdir $gztmpdir
++  echo 'cannot create temporary file' >&2; exit 1;
+ fi || { (exit 127); exit 127; }
+ 
+ gztmp=$gztmpdir/$0
diff --git a/gzip-stderr.patch b/gzip-stderr.patch
--- a/gzip-stderr.patch
+++ b/gzip-stderr.patch
@@ -1,11 +1,11 @@
---- gzip-1.3.6/gzexe.in.orig	2006-11-29 23:51:33.485578500 +0100
-+++ gzip-1.3.6/gzexe.in	2006-11-29 23:52:24.632775000 +0100
-@@ -51,7 +51,7 @@
+--- gzip-1.3.8/gzexe.in.orig	2006-12-13 00:18:36.366398893 +0100
++++ gzip-1.3.8/gzexe.in	2006-12-13 00:19:24.613148319 +0100
+@@ -69,7 +69,7 @@
  
- PATH="BINDIR:$PATH"
- if test $# = 0; then
--  echo "$usage"
-+  echo "$usage" >&2
+ if test $# -eq 0; then
+   echo >&2 "$0: missing operand
+-Try \`$0 --help' for more information."
++Try \`$0 --help' for more information." >&2
    exit 1
  fi
  
