- updated to 1.9 - updated mktemp patch - removed obsolete stderr patch

diff --git a/gzip-mktemp.patch b/gzip-mktemp.patch
--- a/gzip-mktemp.patch
+++ b/gzip-mktemp.patch
@@ -1,11 +1,11 @@
---- gzip-1.3.8/gzexe.in.orig	2006-12-09 07:58:27.000000000 +0100
-+++ gzip-1.3.8/gzexe.in	2006-12-13 00:18:18.193363272 +0100
-@@ -161,7 +161,7 @@
+--- gzip-1.9/gzexe.in.orig	2018-06-12 20:56:23.836235854 +0200
++++ gzip-1.9/gzexe.in	2018-06-12 21:03:07.269564583 +0200
+@@ -169,7 +169,7 @@
  if type mktemp >/dev/null 2>&1; then
-   gztmpdir=`mktemp -dt`
+   gztmpdir=`mktemp -d "${TMPDIR}gztmpXXXXXXXXX"`
  else
--  gztmpdir=/tmp/gztmp$$; mkdir $gztmpdir
-+  echo 'cannot create temporary file' >&2; exit 1;
+-  gztmpdir=${TMPDIR}gztmp$$; mkdir $gztmpdir
++  echo 'cannot create temporary file: missing mktemp program' >&2; exit 1;
  fi || { (exit 127); exit 127; }
  
  gztmp=$gztmpdir/$0
