- by malekith
Changed files:
    gzip-mktemp.patch -> 1.3

diff --git a/gzip-mktemp.patch b/gzip-mktemp.patch
--- a/gzip-mktemp.patch
+++ b/gzip-mktemp.patch
@@ -1,14 +1,15 @@
---- gzip-1.3/gzexe.in.gzexe	Fri Sep 18 00:43:06 1998
-+++ gzip-1.3/gzexe.in	Mon Mar 20 10:28:02 2000
-@@ -94,18 +94,22 @@
- set -C
+diff -ur gzip-1.3/gzexe.in gzip-1.3-/gzexe.in
+--- gzip-1.3/gzexe.in	Fri Sep 18 02:43:06 1998
++++ gzip-1.3-/gzexe.in	Sat Jun  9 16:05:41 2001
+@@ -91,21 +91,21 @@
+     sed 1q $0 > $tmp
+     sed "s|^if tail|if $tail|" >> $tmp <<'EOF'
+ skip=22
+-set -C
  umask=`umask`
  umask 77
 -if tail +$skip $0 | "BINDIR"/gzip -cd > /tmp/gztmp$$; then
-+tmpfile=`mktemp /tmp/gz$$.XXXXXX` || {
-+	echo 'cannot create temporary file' >&2
-+	exit 1
-+}
++tmpfile=`mktemp /tmp/gz$$.XXXXXX` || { echo 'cannot create temporary file' >&2; exit 1; }
 +if tail +$skip $0 | "/bin"/gzip -cd > $tmpfile; then
    umask $umask
 -  /bin/chmod 700 /tmp/gztmp$$
@@ -25,9 +26,10 @@
 -    trap '/bin/rm -f /tmp/gztmp$$; exit $res' 0
 -    (/bin/sleep 5; /bin/rm -f /tmp/gztmp$$) 2>/dev/null &
 -    /tmp/gztmp$$ ${1+"$@"}; res=$?
-+    trap '/bin/rm -f $tmpfile; exit $res' 0
++    trap '/bin/rm -f /tmp/$tmpfile; exit $res' 0
 +    (/bin/sleep 5; /bin/rm -f $tmpfile) 2>/dev/null &
 +    $tmpfile ${1+"$@"}; res=$?
    fi
  else
    echo Cannot decompress $0; exit 1
+
