- use ${TMPDIR:-/tmp} instead directly /tmp.
Changed files:
    gzip-mktemp.patch -> 1.4

diff --git a/gzip-mktemp.patch b/gzip-mktemp.patch
--- a/gzip-mktemp.patch
+++ b/gzip-mktemp.patch
@@ -9,7 +9,7 @@ diff -ur gzip-1.3/gzexe.in gzip-1.3-/gzexe.in
  umask=`umask`
  umask 77
 -if tail +$skip $0 | "BINDIR"/gzip -cd > /tmp/gztmp$$; then
-+tmpfile=`mktemp /tmp/gz$$.XXXXXX` || { echo 'cannot create temporary file' >&2; exit 1; }
++tmpfile=`mktemp ${TMPDIR:-/tmp}/gz$$.XXXXXX` || { echo 'cannot create temporary file' >&2; exit 1; }
 +if tail +$skip $0 | "/bin"/gzip -cd > $tmpfile; then
    umask $umask
 -  /bin/chmod 700 /tmp/gztmp$$
@@ -18,18 +18,18 @@ diff -ur gzip-1.3/gzexe.in gzip-1.3-/gzexe.in
 -  if /bin/ln /tmp/gztmp$$ "/tmp/$prog" 2>/dev/null; then
 -    trap '/bin/rm -f /tmp/gztmp$$ "/tmp/$prog"; exit $res' 0
 -    (/bin/sleep 5; /bin/rm -f /tmp/gztmp$$ "/tmp/$prog") 2>/dev/null &
-+  if /bin/ln $tmpfile "/tmp/$prog" 2>/dev/null; then
-+    trap '/bin/rm -f $tmpfile "/tmp/$prog"; exit $res' 0
-+    (/bin/sleep 5; /bin/rm -f $tmpfile "/tmp/$prog") 2>/dev/null &
-     /tmp/"$prog" ${1+"$@"}; res=$?
+-    /tmp/"$prog" ${1+"$@"}; res=$?
++  if /bin/ln $tmpfile "${TMPDIR:-/tmp}/$prog" 2>/dev/null; then
++    trap '/bin/rm -f $tmpfile "${TMPDIR:-/tmp}/$prog"; exit $res' 0
++    (/bin/sleep 5; /bin/rm -f $tmpfile "${TMPDIR:-/tmp}/$prog") 2>/dev/null &
++    ${TMPDIR:-/tmp}/"$prog" ${1+"$@"}; res=$?
    else
 -    trap '/bin/rm -f /tmp/gztmp$$; exit $res' 0
 -    (/bin/sleep 5; /bin/rm -f /tmp/gztmp$$) 2>/dev/null &
 -    /tmp/gztmp$$ ${1+"$@"}; res=$?
-+    trap '/bin/rm -f /tmp/$tmpfile; exit $res' 0
++    trap '/bin/rm -f ${TMPDIR:-/tmp}/$tmpfile; exit $res' 0
 +    (/bin/sleep 5; /bin/rm -f $tmpfile) 2>/dev/null &
 +    $tmpfile ${1+"$@"}; res=$?
    fi
  else
    echo Cannot decompress $0; exit 1
-
